set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB"
set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g status-interval 5
set -g status-left " #[bold]#S "
set -g status-right " %Y-%m-%d %H:%M "

bind r source-file ~/.tmux.conf \; display-message "tmux configuration reloaded"
bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
