set nocompatible
filetype plugin indent on
syntax enable

set number
set ruler
set showmatch
set incsearch
set ignorecase
set smartcase
set nowrap
set laststatus=2
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set shiftround
set autoindent

autocmd FileType make setlocal noexpandtab
autocmd FileType ruby setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd BufRead,BufNewFile *.json setfiletype json
