# Keep interactive shell startup independent of oh-my-zsh or a vendored plugin tree.
autoload -Uz compinit
compinit -d "${ZDOTDIR:-$HOME}/.zcompdump"

HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory hist_ignore_dups hist_ignore_space share_history
setopt auto_cd interactive_comments

export EDITOR=${EDITOR:-vim}
export VISUAL=${VISUAL:-$EDITOR}

alias ll='ls -lah'
alias la='ls -A'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log --oneline --decorate --graph'
alias gp='git push'
alias gco='git checkout'

if command -v eza >/dev/null 2>&1; then
    alias ls='eza'
    alias ll='eza -lah --git'
fi

if command -v direnv >/dev/null 2>&1; then
    eval "$(direnv hook zsh)"
fi

if [[ -t 0 && -t 1 ]]; then
    for fzf_bindings in /opt/homebrew/opt/fzf/shell/key-bindings.zsh /usr/local/opt/fzf/shell/key-bindings.zsh; do
        if [[ -r "$fzf_bindings" ]]; then
            source "$fzf_bindings"
            break
        fi
    done
fi

if [[ -r "$HOME/.config/rog/private" ]]; then
    source "$HOME/.config/rog/private"
fi
